services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"

  nginx:
    container_name: nginx
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    networks:
      - inception
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    env_file: .env
    secrets:
      - credentials
      - db_password
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: on-failure
    volumes:
      - wordpress:/var/www/wordpress

  adminer:
      build: ./requirements/bonus/adminer
      image: adminer:inception
      container_name: adminer
      restart: on-failure
      networks:
        - inception
      depends_on:
        - mariadb

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/stmaire/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/stmaire/data/mariadb'

networks:
  inception:
    driver: bridge

secrets:
  credentials:
    file: ../secrets/credentials.txt
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
